version: '3'

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    command: python3 app.py
    ports:
      - 127.0.0.1:80:555
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=alpine
      - POSTGRES_PASSWORD=alpine
      - POSTGRES_DB=bd

volumes:
  postgres_data:
