version: '3'

services:
  app:
    build: 
      context: ./
      dockerfile: dockerfile
    command: python3 app.py
    ports:
      - 555:555
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=alpine
      - POSTGRES_PASSWORD=alpine
      - POSTGRES_DB=bd

volumes:
  postgres_data:
