name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [debian-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10.2'
          architecture: 'x64'
        # Устанавливаем зависимости
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: python3 -m pytest -v tests/test_generator.py
